name: Java CI with Maven

# 1. Kích hoạt workflow khi có sự kiện push hoặc pull_request
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    # 1. Thay đổi runs-on để nhận giá trị từ ma trận
    runs-on: ${{ matrix.os }}

    # 2. Định nghĩa ma trận hệ điều hành
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        #run: mvn -B clean test package --file pom.xml(Bài 3)
        run: mvn -B clean test verify --file pom.xml #Bài 5

      # Triển khai action upload-artifact cho JaCoCo Report
      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v4
      # Cấu hình để nó luôn upload báo cáo kể cả khi build bị fail do chưa đạt 80%
        if: always()
        with:
              name: jacoco-report-${{ matrix.os }}
              path: target/site/jacoco/

      # Lưu giữ và xác minh tệp .jar được tạo ra
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-java-app-jar
          path: target/*.jar